### ISSUE TITLE
Mostly empty default-env.json after script-based generation

### ISSUE THREAD

**Issue by ag3silaus** [SAP-samples/teched2020-developer-keynote#25]
Hello
I have empty default.json

![json](https://user-images.githubusercontent.com/58527608/114446619-be69b180-9bd1-11eb-9a96-956d4555115a.PNG)

**Comment by jung-thomas** [comment]
Ok I think there was an upgrade to the CF cli version recently and with it the format of cf env command has changed breaking this script.  @qmacro is away this week and I didn't want to change anything already there. Therefore I've added another script called ./default-env-gen7. https://github.com/SAP-samples/teched2020-developer-keynote/blob/main/cap/brain/default-env-gen7

I tested this script in the Business Application Studio and it works fine. Hopefully this will get you going again until DJ gets back next week and we can look for a more permanent solution.

**Comment by ag3silaus** [comment]
Hello Thomas,
When I ran your script, the Json file was created, but this time I got an error like the picture in the "cds run" command.

![error](https://user-images.githubusercontent.com/58527608/114542669-7a6dbf80-9c58-11eb-81d5-8fed461ad728.PNG)

**Comment by jung-thomas** [comment]
@ag3silaus - I'm not able to recreate that issue. When I run npm start - it starts fine and I see the initialization to the Enterprise Messaging.  When you created the instance of the enterprise messaging service, which plan did you use?  You want to be sure to use the dev plan.  https://github.com/SAP-samples/teched2020-developer-keynote/tree/main/messagebus

![image](https://user-images.githubusercontent.com/12159356/114597398-bdcb2c80-9c5e-11eb-87de-680bbb898429.png)

**Comment by jung-thomas** [comment]
By any chance did you change the version of the @sap/cds module in package.json of the /cap/brain?  If I update my project to 5.x version of CAP then I do get that same error you received. However when I go back to the specific version used in this repo (4.4.7) and use npm install then it starts fine again.

 "dependencies": {
    "@sap/cds": "4.4.7",
    "@sap/hana-client": "^2.5",
    "@sap/xb-msg-amqp-v100": "latest",
    "console-log-level": "^1.4.1",
    "express": "^4",
    "sqlite3": "^5.0"
  },

After install check from the terminal in this folder with a "cds version" to see what version it is using.

**Comment by ag3silaus** [comment]
Hallo Thomas,
i create new CAP in my BAS and i didnt receive this error. I will use this app for the future lessons. But i want to know also where problem is? Thank you for your patience.

![problem](https://user-images.githubusercontent.com/58527608/114617448-6d78bc80-9ca8-11eb-84eb-8a0c45eb45ae.PNG)

**Comment by qmacro** [comment]
Hi @ag3silaus I'll be back from holiday next week and I'm looking forward to taking a look here too. Speak soon. Cheers. DJ

**Comment by ag3silaus** [comment]
Hi DJ,
I created a new Dev Space and came up to the Charity component section and
I also started to Diving into messaging on SAP Cloud Platform series😊. But
I would like to know where the Problem in my old Dev Space is.
Thank you for your help. Have a nice day. Regards


DJ Adams ***@***.***>, 16 Nis 2021 Cum, 12:43 tarihinde şunu
yazdı:

**Comment by qmacro** [comment]
Hi @ag3silaus we addressed this in the [Open Working live stream](https://www.youtube.com/watch?v=0XlzLq9_om0), hope this is OK. Basically you got a single `}` because the output of `cf env` at version 7 is different to the output at version 6 and the `sed` based parsing was too brittle to cope. My fault entirely. Tom corrected this at the time with a temporary version, the associated PR makes this permanent.

**Comment by qmacro** [comment]
Hi again @ag3silaus on the cds version and enterprise messaging "kind", there are changes relating to single/multi tenancy support and you may need to use `enterprise-messaging-shared` in newer versions of cds. See the [live stream](https://www.youtube.com/watch?v=0XlzLq9_om0) around 100 minutes in.
