### ISSUE TITLE
Kyma Brain Component Deployment Error

### ISSUE THREAD

**Issue by ag3silaus** [SAP-samples/teched2020-developer-keynote#27]
Hallo guys,
When i tried to deploy my Brain Docker Image from Github Actions, i am getting this Error.

![backoff-error](https://user-images.githubusercontent.com/58527608/119353283-fd942380-bca2-11eb-93cd-9c5890774de9.PNG)

then i tried to run this Pod and i got this Error.

![pod-error](https://user-images.githubusercontent.com/58527608/119353350-0f75c680-bca3-11eb-8321-bbb7cf62c44e.PNG)

Although I was able to activate the EM Credential locally, I could not activate it for Docker Image. I would be glad if you could help.

**Comment by IObert** [comment]
The error message says that the credentials are missing. I guess this means you didn't include them in the env var of the docker image (or a linked K8S config map or secret)

**Comment by ag3silaus** [comment]
Ty DJ for all. Guys you can find the answer 
here ==> https://www.youtube.com/watch?v=TG4mWXPrzh0&ab_channel=SAPDevelopers

**Comment by qmacro** [comment]
We got together on the live stream and proved to ourselves by working through it together that @IObert 's observation was spot on 🚀
